### ISSUE TITLE
Feature: Add reminder for contributors to fill out the whole PR template in lesson 05.

### ISSUE THREAD

**Issue by Haimantika** [open-sauced/intro#140]
### Type of feature

🍕 Feature

### Current behavior

In [lesson 05](https://github.com/open-sauced/intro/blob/main/05-how-to-contribute-to-open-source.md) of the course, where contributors are adding themself to the guestbook, there is no reminder for contributors to fill out the issue template completely and this is something that one can miss. It will be nice to add a point about it. 

### Suggested solution

1. Go to [lesson 05- how-to-contribute-to-open-source](https://github.com/open-sauced/intro/blob/main/05-how-to-contribute-to-open-source.md), under [Let’s get practical](https://github.com/open-sauced/intro/blob/main/05-how-to-contribute-to-open-source.md#lets-get-practical).
2.  Make the following changes in point 11 👇

```
11. Go to your forked repository on GitHub. Create a pull request with the title `feat: Add <@github-username> as a contributor` and fill in all areas in the pull request form.

     !> Your pull request will be marked as invalid and may be closed if the form is incomplete.
 ```

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### Contributing Docs

- [X] I agree to follow this project's Contribution Docs

**Comment by CBID2** [comment]
Hi @Haimantika. Point 7 does mention fill out the required information, so I’m not sure if adding the note is necessary. What do you think @adiati98?

**Comment by Haimantika** [comment]
Hi @CBID2 it does say to fill in the required information, yet I missed filling the description, and there might be more contributors who miss it. So either a note or a in the same line if we can mention in bold to fill **all** information, it will be helpful.

**Comment by FatumaA** [comment]
Hi,
I think Haimantika has a point here, it would be useful for very new contributors if there was an explicit point on issue templates and the importance/why they should be filled in completely.

**Comment by adiati98** [comment]
@Haimantika thanks for raising this issue! 🙌

I think this is a good idea. ✨
However, I have another thought for this that I need to think through. 

I see that the same issue is going on around open source and not only here. Folks are not completing PR forms, even with explicit instructions.

---

For now, I see a chance to update point 11 in "Let's Get Practical" section because I believe folks are following this tutorial to contribute to the guestbook repo.

https://github.com/open-sauced/intro/blob/67c7526bcd2327e69ff65269646932c68ec12fc6/05-how-to-contribute-to-open-source.md?plain=1#L172

If you can update this issue to address it, that would be great.

We can update it as follow:

```markdown
11. Go to your forked repository on GitHub. Create a pull request with the title `feat: Add <@github-username> as a contributor` and fill in all areas in the pull request form.

    !> Your pull request will be marked as invalid and may be closed if the form is incomplete.
```

**Comment by Haimantika** [comment]
> @Haimantika thanks for raising this issue! 🙌
> 
> I think this is a good idea. ✨ However, I have another thought for this that I need to think through.
> 
> I see that the same issue is going on around open source and not only here. Folks are not completing PR forms, even with explicit instructions.
> 
> For now, I see a chance to update point 11 in "Let's Get Practical" section because I believe folks are following this tutorial to contribute to the guestbook repo.
> 
> https://github.com/open-sauced/intro/blob/67c7526bcd2327e69ff65269646932c68ec12fc6/05-how-to-contribute-to-open-source.md?plain=1#L172
> 
> If you can update this issue to address it, that would be great.
> 
> We can update it as follow:
> 
> ```
> 11. Go to your forked repository on GitHub. Create a pull request with the title `feat: Add <@github-username> as a contributor` and fill in all areas in the pull request form.
> 
>     !> Your pull request will be marked as invalid and may be closed if the form is incomplete.
> ```

Yes! This is a great suggestion. Thanks. Will update the repo accordingly.

**Comment by Haimantika** [comment]
@adiati98 made the changes in the issue. Let me know what you think.

**Comment by adiati98** [comment]
> @adiati98 made the changes in the issue. Let me know what you think.

As I mentioned in my comment, can you please change the "Contributor Workflow" section to "Let's Get Practical"? And give indentation for the last sentence, as it would be part of the point 11. Thanks, @Haimantika!

**Comment by adiati98** [comment]
Hi @CBID2 ,

Thank you for your prompt action! 😊

For your future reference, we want to first ask contributor if they want to work on the issue before assigning, even if they're the one who created it. There are cases where contributors are creating issues to address something but don't have the intention to work on it. 🙂

As there's a request to update the issue, it would be great to wait until the issue is updated before removing the `needs triage` label.

**Comment by Haimantika** [comment]
Thanks for assigning the issue to me @CBID2, I will work on it later today. Also @adiati98 let me know if everything is fine now.

**Comment by adiati98** [comment]
> Thanks for assigning the issue to me @CBID2, I will work on it later today. Also @adiati98 let me know if everything is fine now. 

Yes. 👍

**Comment by Haimantika** [comment]
> > Thanks for assigning the issue to me @CBID2, I will work on it later today. Also @adiati98 let me know if everything is fine now.
> 
> Yes. 👍

PR raised :)
